# Generated by Django 3.2 on 2022-07-04 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Airport Code')),
                ('name', models.CharField(max_length=150, verbose_name='Airport Name')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=20, verbose_name='Flight Number')),
                ('take_off', models.DateTimeField(verbose_name='Take Off Time')),
                ('landing', models.DateTimeField(verbose_name='Landing Time')),
                ('from_airport', models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, related_name='from_airport', to='flight.airport')),
                ('to_airport', models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, related_name='to_airport', to='flight.airport')),
            ],
        ),
    ]
